apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: davem
  description: this is a test
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: group:default/maltinator
  lifecycle: experimental
